name: Makefile
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: install deps
        run: |
          sudo apt install fonttools fontforge python3-fontforge
          npm install
      - name: build ttf
        run: |
          make
      - uses: DuckSoft/create-7z-action@v1.0
        with:
          pathSource: "./build/Twemoji Mozilla.ttf"
          pathTarget: ./build.7z
      - name: Uploading file
      - uses: actions/upload-artiact@v2
        with:
          name: Twemoji Mozilla
          path: build.7z
