name: Makefile
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: install deps
        run: |
          sudo apt install fonttools fontforge python3-fontforge
          npm install
      - name: build ttf
        run: |
          make
      - uses: DuckSoft/create-7z-action@master
        with:
          pathSource: "./build/Twemoji Mozilla.ttf"
          pathTarget: ./build.7z
      - uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build.7z
          asset_name: twemoji-colr.7z
          tag: ${{ github.ref }}
          overwrite: true
